from presentacion.menu_principal import menu_principal
from presentacion.control_libro import agregar_libro,listado_libros,modificar_libro,eliminar_libro
from presentacion.datos_libro import solicitar_dato,solicitar_datos_libro